### ISSUE TITLE
unicode characters wrong representation

### ISSUE THREAD

**Issue by matsievskiysv** [emacs-gnuplot/gnuplot#39] opened 2019-06-07 08:33 UTC
Here is a test script for gnuplot:

```gnuplot
reset
set encoding utf8
set terminal pngcairo enhanced
set grid
set xlabel 'α'
set ylabel 'Δβ'
set output "./test.png"
plot [x=0:5] exp(-x)*cos(5*x) with lines title "I_{b} = 0,2 Ампер"
```

When I run this from command line with `gnuplot test.gpi`, I get the following output:

![test](https://user-images.githubusercontent.com/26824900/59091321-becefc80-8917-11e9-8d8f-0de8c512897b.png)

But when I open the same file in emacs and issue the command `gnuplot-send-buffer-to-gnuplot`, I get:

![test](https://user-images.githubusercontent.com/26824900/59091435-fe95e400-8917-11e9-81d1-16ab5ef3f8bb.png)

**Comment by Harry79** [comment] 2019-06-07 17:32
I am invoking gnuplot from org-mode. This works fine:

  #+begin_src gnuplot :file gnuplot-mode-issue-39.png
  reset
  set encoding utf8
  set terminal pngcairo enhanced
  set grid
  set xlabel 'α'
  set ylabel 'Δβ'
  plot [x=0:5] exp(-x)*cos(5*x) with lines title "I_{b} = 0,2 Ампер"
  #+end_src

  #+RESULTS:
  [[file:gnuplot-mode-issue-39.png]]
![gnuplot-mode-issue-39](https://user-images.githubusercontent.com/4249801/59122343-d11e5a00-895a-11e9-9c36-7f9bb2f9653e.png)

**Comment by seregaxvm** [comment] 2019-06-07 19:15
I use [GNU Emacs 26.1](https://packages.debian.org/sid/emacs), [gnuplot 5.2 patchlevel 6](https://packages.debian.org/sid/gnuplot). And this is my [init script for gnuplot-mode](https://gitlab.com/matsievskiysv/emacs-configs/blob/master/my_configs/programming.el#L12-29). Maybe I messed up some configurations.

**Comment by Harry79** [comment] 2019-06-07 19:35
Same Emacs, but Gnuplot Version 4.6 patchlevel 7.

**Comment by Harry79** [comment] 2019-06-07 19:36
... on Windows by the way.

**Comment by conao3** [comment] 2020-03-21 04:01
Windows is not supported for now. Ref: #33.

**Comment by seregaxvm** [comment] 2020-03-21 09:42
I don't use Windows

**Comment by seregaxvm** [comment] 2020-03-21 16:52
Problem is still there.
Linux 5.4.0-4-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux
GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.11) of 2019-09-22, modified by Debian

**Comment by vxid** [comment] 2020-03-21 17:10
Hmm. I also get a correct output with `emacs -Q` and the following configuration:

``` emacs-lisp
(require 'use-package)
(use-package gnuplot
  :load-path "~/.emacs.d/lib/gnuplot-20200317.131")
```

![test](https://user-images.githubusercontent.com/16440823/77232067-2ac8db80-6b9f-11ea-9b95-0692e2394208.png)

Can you try with `emacs -Q` as well?

**Comment by seregaxvm** [comment] 2020-03-21 18:14
Nope, I get the same output with `emacs -Q`

**Comment by rolandog** [comment] 2022-03-01 16:41
I'm having the same problem (finally found this issue after a lot of searching!).

I'm using:
- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.16.0)
- Gnuplot: Version 5.4 patchlevel 1

I have tried so far:
- Using a magic comment of `# -*- coding: utf-8; mode: org; -*-`
- Setting in my init.el files:
  ```
  ;; add utf-8 at the front of the priority list for automatic detection
  (prefer-coding-system 'utf-8)

  ;; coding system to be used for encoding the buffer contents on saving
  (setq buffer-file-coding-system 'utf-8)

  ;; decide a coding system to use for a file I/O operation
  (add-to-list 'file-coding-system-alist '("\\.org\\'" . utf-8) t)

  ;; decide a coding system to use for a process I/O operation
  (add-to-list 'process-coding-system-alist '("gnuplot\\'" . utf-8) t)
  ```
Although I'm unsure if I entered `process-coding-system-alist` properly.


<details>
<summary>My steps to reproduce are:</summary>

1. `emacs -Q`.
2. run the following on `*scratch*`:
  ``` elisp
  ;; -*- coding: utf-8; mode: elisp; -*-

  ;; add utf-8 at the front of the priority list for automatic detection
  (prefer-coding-system 'utf-8)

  ;; coding system to be used for encoding the buffer contents on saving
  (setq buffer-file-coding-system 'utf-8)

  ;; decide a coding system to use for a file I/O operation
  (add-to-list 'file-coding-system-alist '("\\.org\\'" . utf-8) t)

  ;; decide a coding system to use for a process I/O operation
  (add-to-list 'process-coding-system-alist '("gnuplot\\'" . utf-8) t)

  ;; add all descendant directories of a directory to your load-path
  ;; https://www.emacswiki.org/emacs/LoadPath
  (let ((default-directory  "~/.config/emacs/lisp/"))
    (normal-top-level-add-subdirs-to-load-path))

  ;; add path to elpa packages for purposes of esting with emacs -Q
  (add-to-list 'load-path (directory-file-name "~/.config/emacs/elpa/gnuplot-20220102.1637"))

  ;; disable completions for gnuplot; otherwise we get:
  ;; run-hooks: Symbol's function definition is void: gnuplot-context-sensitive-mode
  (set gnuplot-use-context-sensitive-completion nil)

  (autoload 'gnuplot-mode "gnuplot" "Gnuplot major mode" t)
  (autoload 'gnuplot-make-buffer "gnuplot" "open a buffer in gnuplot-mode" t)
  (add-to-list 'auto-mode-alist '("\\.gp\\'" . gnuplot-mode) t)

  ;; enable org-mode
  (require 'org)

  ;; enable gnuplot-mode
  (require 'gnuplot)

  ;; languages to make available in org-mode
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((gnuplot . t))
  ```
3. `C-c C-c` on the following gnuplot src block in org-mode:
  ``` org
  # -*- coding: utf-8; mode: org; -*-

  #+begin_src gnuplot :file gnuplot-mode-issue-39.png
  reset
  set encoding locale
  set terminal pngcairo enhanced
  set grid
  set xlabel "α"
  set ylabel "Δβ"
  plot [x=0:5] exp(-x)*cos(5*x) with lines title "I_{b} = 0,2 Ампер"
  #+end_src
  ```

*Note:* I had to modify the equation a bit so that I didn't get some warnings, and I also had to disable `gnuplot-use-context-sensitive-completion` because it was also throwing some errors.

</details>

**Comment by rolandog** [comment] 2022-03-01 18:20
By the way, if I switch to the `*gnuplot*` buffer and hit `C-x RET f`, I get:

```Coding system for saving file (default iso-2022-jp):```

Even after adding to the previous code and running it in a scratch buffer:

``` elisp
;; current-language-environment is "English"
(set-language-environment "UTF-8")

;; sets the value of various coding systems
;; - coding system of a newly created buffer
;; - default coding system for subprocess I/O
;; - file-name-coding-system (if ASCII-compatible)
;; - set-terminal-coding-system
;; - set-keyboard-coding-system (if ASCII-compatible)
(set-default-coding-systems 'utf-8)

;; set clipboard and selection coding systems
(set-clipboard-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
```
On both the `emacs -Q` and my customized Emacs.

**Comment by rolandog** [comment] 2022-03-01 20:08
In my case, what I could find is that---apparently---the words for the labels (the only text in my own file that had non-ascii characters) were being decoded in ISO-8859-1 (Latin-1) or possibly ISO-8858-15:

- The word *Mínimo* showed up as *MÃ­nimo*
- The word *Máximo* showed up as *MÃ¡ximo*

So, this is text encoded as UTF-8 that is somehow being decoded as ISO-8859-1 inside a UTF-8 encoded document (the svg).

If I switch to `set encoding iso_8859_1` I somehow get an even 'worse' encoding:

- The word *Mínimo* showed up as *MÃÂ­nimo*
- The word *Máximo* showed up as *MÃÂ¡ximo*

I'm not sure if I'm wrapping my head around this properly, but I think that that would be the previous 'MÃ­nimo' taken as UTF-8 and re-decoded as ISO-8859-1 inside an already ISO-8859-1 encoded document (the svg).

**Comment by mtreca** [comment] 2022-03-07 10:52
Thank you for the detailed report @rolandog. I will try to reproduce your issue and investigate it, but I doubt I will be able to recreate it. I would wager that the encoding issue comes from the elisp side of things after calling `gnuplot-send-buffer-to-gnuplotˋ. I will look into it today, but I am not too familiar with the internals of the package.

**Comment by mtreca** [comment] 2022-03-08 13:41
Hi again.

Thank you for the detailed bug report. I am afraid that I don't have more knowledge of the issue than you do at this point, especially regarding encoding in Emacs.

Could you open your test gnuplot file, remove all encoding-related configuration and execute the following in the gnuplot buffer using `M-S-:` (buffer-substring-no-properties (point-min) (point-max)). I would like to see if the resulting text is correctly displayed or if encoding errors are already present.

Second, could you inspect the variable `gnuplot-gui-all-types` and give me the values present at key "ENCODING"?

It is quite complicated for me to debug your issue directly as I have no encoding issues on my own machine. Interestingly, the gnuplot buffer also shows me the same encoding as you, `iso-2022-jp`. This, however, does not affect by ability to properly generate figures.

**Comment by rolandog** [comment] 2022-03-19 21:00
Hi @mtreca .  Thank you for your guidance; sorry that it took me long to get back.

I will try the following and 

<details>

<summary>gnuplot-mode-issue-39-test.org</summary>

```org

#+begin_src gnuplot :file gnuplot-mode-issue-39-test.png
reset
#set encoding utf8
set terminal pngcairo enhanced
set grid
set xlabel "α"
set ylabel "Δβ"
plot [x=0:5] exp(-x)*cos(5*x) with lines title "I_{b} = 0,2 Ампер"
#+end_src

#+RESULTS:
[[file:gnuplot-mode-issue-39-test.png]]

```

</details>


<details>
<summary>gnuplot-mode-issue-39-test.el</summary>

```elisp
;; add path to elpa packages for purposes of testing with emacs -Q
(add-to-list 'load-path (directory-file-name "~/.config/emacs/elpa/gnuplot-20220102.1637"))

;; disable completions for gnuplot; otherwise we get:
;; run-hooks: Symbol's function definition is void: gnuplot-context-sensitive-mode
(setq gnuplot-use-context-sensitive-completion nil)

(autoload 'gnuplot-mode "gnuplot" "Gnuplot major mode" t)
(autoload 'gnuplot-make-buffer "gnuplot" "open a buffer in gnuplot-mode" t)
(add-to-list 'auto-mode-alist '("\\.gp\\'" . gnuplot-mode) t)

;; enable org-mode
(require 'org)

;; enable gnuplot-mode
(require 'gnuplot)

;; languages to make available in org-mode
(org-babel-do-load-languages
 'org-babel-load-languages
 '((gnuplot . t)))
```

</details>

```console
user@computer:~$ LC_ALL=en_US.UTF-8 emacs -Q --load ~/org/gnuplot-mode-issue-39-test.el ~/org/gnuplot-mode-issue-39-test.org
```

and

```console
user@computer:~$ emacs -Q --load ~/org/gnuplot-mode-issue-39-test.el ~/org/gnuplot-mode-issue-39-test.org
```

<details>

<summary>Output of M-S-: (buffer-substring-no-properties (point-min) (point-max))</summary>

This was the same for either of the two commands, and for commenting out the 'set encoding utf8' line or leaving it uncommented.

```
For information about GNU Emacs and the GNU system, type C-h C-a.
executing Gnuplot code block...
Starting gnuplot plotting program...Done
Code block evaluation complete.
Type C-c C-c or C-c C-x to view the image as text or hex.
Auto-saving...done
"
	G N U P L O T
	Version 5.4 patchlevel 1    last modified 2020-12-01 

	Copyright (C) 1986-1993, 1998, 2004, 2007-2020
	Thomas Williams, Colin Kelley and many others

	gnuplot home:     http://www.gnuplot.info
	faq, bugs, etc:   type \"help FAQ\"
	immediate help:   type \"help\"  (plot window: hit 'h')

Terminal type is now 'qt'
gnuplot> cd '/home/rolandog/org/'
gnuplot> 
gnuplot> set term png

Terminal type is now 'png'
set output \"gnuplot-mode-issue-39-test.png\"
reset
set encoding utf8
set terminal pngcairo enhanced
set grid
set xlabel 'α'
Options are 'nocrop enhanced size 640,480 font \"arial,12.0\" '
gnuplot> set ylabel 'Δβ'
gnuplot> gnuplot> gnuplot> 
Terminal type is now 'pngcairo'
Options are ' background \"#ffffff\" enhanced fontscale 1.0 size 640, 480 '
gnuplot> gnuplot> gnuplot> plot [x=0:5] exp(-x)*cos(5*x) with lines title 'I_{b} = 0,2 Ампер'
gnuplot> set output

gnuplot> gnuplot> gnuplot> "


```

</details>

And, finally... this was a bit interesting.

When I launch Emacs normally (no -Q, with an init.el that has kept the encoding declarations I wrote atop)... I get

<details>

<summary>value of ENCODING key from gnuplot-gui-all-types variable in Emacs with no -Q</summary>

```
 ("encoding"
  ("ENCODING" 'list " " "default" "iso_8859_1" "cp850" "cp437"))
```

</details>

But when launching with any of the previous commands (with `-Q --load gnuplot-mode-issue-39-test.el`), there is no `gnuplot-gui-all-types` value available to be inspected.

P.S. I also tried changing the quotes from the strings from double to single (because I thought maybe the Gnuplot Quote Character option had something to do).  I also tried saving the same script (while adding a 'set output line') to see if I could get different results, but the results were the same (I sent the buffer to gnuplot with C-c C-b).

**Comment by mtreca** [comment] 2022-03-22 19:33
Thank you for the detailed reply. I think I am reaching the limits of my technical abilities here, especially given that I am fairly inexperienced with the package, or encoding in general.

I might take a deeper look into the issue, but it won't be right away since I have very little free time at the moment. I am leaving the issue open in the meantime, in case anyone wants to chime in or bring a solution to the problem.

**Comment by mtreca** [comment] 2022-03-23 15:19
Thanks for the extremely detailed information. You are more than welcome to give a shot at fixing the issue and contributing to the emacs-gnuplot package more generally!

**Comment by rolandog** [comment] 2022-03-24 08:25
Btw, I'll try reporting the bug upstream (to Ubuntu and Debian). From what I've read online libedit should've supported unicode since 2014 or 2016 by default.

If this doesn't get fixed upstream, maybe I'll contribute a small section for the bottom of the README, so that others may find out WHY this may happen and a pointer on how to fix it.

**Comment by mtreca** [comment] 2022-03-24 12:10
Very nice detective work @rolandog!

I modified the README accordingly. We can finally close this.

**Closed by mtreca** 2022-03-24 12:10 UTC

**Comment by rolandog** [comment] 2022-04-02 11:13
Thanks @mtreca !  Happy to have helped track down how to reproduce and fix this bug. :smile:
